# Generated by Django 4.0.6 on 2022-09-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Particulars', models.CharField(max_length=255)),
                ('Vch_Type', models.CharField(max_length=255)),
                ('Vch_No', models.IntegerField()),
                ('Debit_Amount', models.IntegerField()),
                ('Credit_Amount', models.IntegerField()),
                ('Month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.months')),
                ('Voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vouchers')),
            ],
        ),
    ]
