# Generated by Django 4.0.6 on 2022-09-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_voucher_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher_register',
            name='Credit_Amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='voucher_register',
            name='Debit_Amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
