# Generated by Django 4.0.6 on 2022-09-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_voucher_register_vch_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Voucher', models.IntegerField()),
                ('Cancelled', models.IntegerField()),
                ('Month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.months')),
                ('Voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vouchers')),
            ],
        ),
    ]
