# Generated by Django 4.0.6 on 2022-09-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_voucher_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher_count',
            name='Cancelled',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='voucher_count',
            name='Total_Voucher',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
