# Generated by Django 4.0.6 on 2022-09-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_voucher_count_cancelled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher_count',
            name='Cancelled',
        ),
    ]
