# Generated by Django 4.0.6 on 2022-09-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_voucher_count_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField(blank=True, default='', null=True)),
                ('Voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vouchers')),
            ],
        ),
    ]
