# Generated by Django 4.0.6 on 2022-09-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='Total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
