# Generated by Django 4.0.6 on 2022-09-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_total_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accounts_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts_Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField(blank=True, default='', null=True)),
                ('Accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounts')),
            ],
        ),
    ]
