# Generated by Django 4.0.6 on 2022-09-17 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_accounts_accounts_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistics_Accounts_Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='statistics_Total_Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Voucher_count',
            new_name='statistics_Voucher_count',
        ),
        migrations.RenameModel(
            old_name='Voucher_Register',
            new_name='statistics_Voucher_Register',
        ),
        migrations.RemoveField(
            model_name='total',
            name='Voucher',
        ),
        migrations.RenameModel(
            old_name='Accounts',
            new_name='statistics_Accounts',
        ),
        migrations.RenameModel(
            old_name='Vouchers',
            new_name='statistics_Vouchers',
        ),
        migrations.DeleteModel(
            name='Accounts_Total',
        ),
        migrations.DeleteModel(
            name='Total',
        ),
        migrations.AddField(
            model_name='statistics_total_voucher',
            name='Voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statistics_vouchers'),
        ),
        migrations.AddField(
            model_name='statistics_accounts_total',
            name='Accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statistics_accounts'),
        ),
    ]
